### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted

### ISSUE THREAD

**Issue by thomas2045** [ilovemilk/ransomware_detection#6]
I got errors like this in the admin log, when my Mac client tried to sync several files with sizes between 300 and 1600 MB (Limit on the server was 2GB):

`Allowed memory size of 536870912 bytes exhausted (tried to allocate 67108872 bytes) at /var/www/html/nextcloud/apps/ransomware_detection/lib/Analyzer/EntropyAnalyzer.php#155`

The client showed 
`500 internal Server error`

After deactivating the plugin the files synced perfectly.

Infos:
```
Ransomware recovery	0.4.1
Nextcloud: 14.0.3.0
Version: 7.2.10
Arbeitspeicher-Grenzwert: 512 MB  <-- this may be the problem?
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 4 GB
```

hope this helps,

Thomas

**Comment by ilovemilk** [comment]
Hi Thomas,

Thank you for reporting the problem.

You are right the problem is that your files are bigger than your RAM because I perform an analysis of files by getting all the data at once but I think I can fix this easily together with bumping the compatibility to Nextcloud 15.

I try to get this done in the next week and will notify you! :)

Matthias

**Comment by ilovemilk** [comment]
Hi Thomas,

I released version 0.4.2 fixing the memory exhaustion bug.

It would be great if you could test it and write me back if everything works fine now! :)

Matthias

**Comment by thomas2045** [comment]
Hi Matthias, 

thanks a lot, I activated it and will observe if there are errors.
Renaming and syncing a 600mb file worked so far.

greets Thomas

**Comment by ilovemilk** [comment]
Perfect!

I will mark this issue as resolved.

Matthias
